### ISSUE TITLE
support consuming TRAPI v1.1 APIs

### ISSUE THREAD

**Issue by newgene** [biothings/call-apis.js#18]
Note a few small query graph property name changes:

https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ChangeLog.md

**Comment by newgene** [comment]
* need to consume new /meta_knowledge_graph endpoint to get the predicates information
* update input query graph to use new v1.1 format (mostly change word to its plural)

**Comment by newgene** [comment]
Can potentially test with this TRAPI v1.1 example:

http://smart-api.info/registry?q=305a2909830b776df7a02b7207e4acc5

e.g. this should work:

http://api.bte.ncats.io/v1/smartapi/305a2909830b776df7a02b7207e4acc5/meta_knowledge_graph

**Comment by newgene** [comment]
Also test an actual TRAPI query to a specific http://api.bte.ncats.io/v1/smartapi/<api_id>/query URL to confirm it's working.

**Comment by marcodarko** [comment]
Update:
[OpenPredict](http://smart-api.info/registry?q=e9f69b81e755e163fdf6c41a2b5e07c0) (trapi 1.1.0) works for testing this endpoint:
https://api.bte.ncats.io/v1/smartapi/e9f69b81e755e163fdf6c41a2b5e07c0/meta_knowledge_graph

However, the previous test url provided uses [Automat KEGG](http://smart-api.info/registry?q=305a2909830b776df7a02b7207e4acc5) (trapi 1.1.0) and it does not work (but should), it appears that this API is not making it into the specs file collected by our cron job that looks at the registry.  We need to investigate why that is.

**Comment by marcodarko** [comment]
@andrewsu @newgene I think the reason that API ([Automat KEGG](https://smart-api.info/ui/305a2909830b776df7a02b7207e4acc5) ) doesn't appear is because they have "/1.1/meta_knowledge_graph" instead of "/meta_knowledge_graph" thus failing our check and not being included. What should we do about it?

**Comment by marcodarko** [comment]
*Note on why some of these APIs don't work for this endpoint:  `/v1/<ID>/meta_knowledge_graph`
This endpoint will ultimately look through the specs.json (response from a query to SmartAPI for all translator APIs) for this API and look in the paths for a property "x-bte-kgs-operations" in them, if that is not found the operations returned will be 0 and that triggers an "error" on our side but it simply means that nothing was found. As I understand, this was the old way to specify operations now moved to its own endpoint: `/meta_knowledge_graph `.  How do we want to handle such cases? or is this endpoint going to be deprecated at some point?

**Comment by colleenXu** [comment]
Can this issue be closed? I have another one currently open that's related...https://github.com/biothings/BioThings_Explorer_TRAPI/issues/269
